# ruff.toml — Quality + Documentation checks for LaunchLens

line-length = 100
target-version = "py310"

[lint]
select = [
    "E",    # pycodestyle (basic errors)
    "F",    # pyflakes (undefined names, etc.)
    "I",    # isort (import sorting)
    "D",    # pydocstyle (docstrings)
    "ANN",  # flake8-annotations (type hints)
    "N",    # pep8-naming
    "UP",   # pyupgrade (modern Python idioms)
    "B",    # bugbear (likely bugs or bad practices)
]

ignore = [
    "D107",  # Missing docstring in __init__
    "D203",  # One blank line before class docstring (conflicts with D211)
    "D213",  # Multi-line docstring summary should start at the second line
    "N806",  # Variable in function should be lowercase (we allow X/y for ML)
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-annotations]
mypy-init-return = true
allow-star-arg-any = false

[lint.per-file-ignores]
"*/__init__.py" = ["D104"]

